### ISSUE TITLE
Hang out in Matte theme

### ISSUE THREAD

**Issue by ivanthesexy** [Haltroy/Yorot#17]
*Reported to my IG account*
Korot stops responding on Matte theme, this problem might happen to Yorot-Win32 too.

**Screenshots:**

![IMG_20210227_082027_911.jpg](https://user-images.githubusercontent.com/78353549/109376325-c517c000-78d4-11eb-8fa2-6ca8ea2f1ef7.jpg)![IMG_20210227_082025_169.jpg](https://user-images.githubusercontent.com/78353549/109376328-c77a1a00-78d4-11eb-8c4a-8a07e0aa4054.jpg)

**Reason:**
I have no idea but it even hanged out in every computer that I tested it out. Probably because the heavy workload on start. This probably won't happen to Yorot.

**Comment by Haltroy** [comment]
To be honest, I forgot to do these things but I'll try my best to stick to my projects.
This problem will only occur in Yorot-Win32 since Win32 packages (either CefSharp or EasyTabs, most likely EasyTabs) are going to be different than other projects such as Yorot-Avalonia (CefSharp replaced by either CefNet or CefGlue and EasyTabs will be recreated just for Yorot-Avalonia) so no worries on other platforms. And I'll start investigating on this issue by opening example and easily debuggable applications into a virtual machine that contains the environment that we need to find the problem.
Either that or the guy who texted me had a problem in his computer.
